package com.nltimer.core.designsystem.icon

enum class EmojiCategory {
    FREQUENT,
    EXPRESSIONS,
    GESTURES,
    ANIMALS,
    FOOD,
    TRAVEL,
    ACTIVITIES,
    OBJECTS,
    NATURE,
    SYMBOLS
}

data class EmojiEntry(
    val emoji: String,
    val name: String,
    val category: EmojiCategory,
    val keywords: List<String>
)

object EmojiCatalog {

    private val _emojis: List<EmojiEntry> = listOf(
        EmojiEntry("😀", "grinning", EmojiCategory.FREQUENT, listOf("笑脸", "开心", "grin", "smile", "happy")),
        EmojiEntry("😂", "joy", EmojiCategory.FREQUENT, listOf("笑哭", "笑死了", "笑出眼泪", "laugh", "cry", "tears")),
        EmojiEntry("🥰", "smiling_face_with_hearts", EmojiCategory.FREQUENT, listOf("爱你", "比心", "love", "hearts", "adore")),
        EmojiEntry("😍", "heart_eyes", EmojiCategory.FREQUENT, listOf("花痴", "爱心眼", "love", "heart", "eyes")),
        EmojiEntry("🤣", "rofl", EmojiCategory.FREQUENT, listOf("笑趴", "笑死了", "ROFL", "laugh", "floor")),
        EmojiEntry("😊", "blush", EmojiCategory.FREQUENT, listOf("害羞", "微笑", "blush", "shy", "smile")),
        EmojiEntry("😭", "sob", EmojiCategory.FREQUENT, listOf("大哭", "哭死了", "sob", "cry", "sad")),
        EmojiEntry("🥺", "pleading_face", EmojiCategory.FREQUENT, listOf("求求你", "可怜", "plead", "puppy", "eyes")),
        EmojiEntry("😎", "sunglasses", EmojiCategory.FREQUENT, listOf("酷", "墨镜", "cool", "sunglasses", "swag")),
        EmojiEntry("🤔", "thinking", EmojiCategory.FREQUENT, listOf("思考", "想想", "think", "hmm", "wonder")),
        EmojiEntry("😅", "sweat_smile", EmojiCategory.FREQUENT, listOf("尴尬笑", "汗", "awkward", "sweat", "phew")),
        EmojiEntry("👍", "thumbsup", EmojiCategory.FREQUENT, listOf("赞", "好的", "like", "thumbs", "up")),
        EmojiEntry("👎", "thumbsdown", EmojiCategory.FREQUENT, listOf("踩", "不行", "dislike", "thumbs", "down")),
        EmojiEntry("❤️", "red_heart", EmojiCategory.FREQUENT, listOf("爱心", "爱", "love", "heart", "red")),
        EmojiEntry("🔥", "fire", EmojiCategory.FREQUENT, listOf("火", "厉害", "fire", "hot", "lit")),
        EmojiEntry("🎉", "tada", EmojiCategory.FREQUENT, listOf("庆祝", "派对", "party", "celebrate", "congrats")),
        EmojiEntry("✨", "sparkles", EmojiCategory.FREQUENT, listOf("闪亮", "特效", "sparkle", "shine", "magic")),
        EmojiEntry("💯", "hundred", EmojiCategory.FREQUENT, listOf("满分", "一百", "perfect", "100", "score")),
        EmojiEntry("🙏", "pray", EmojiCategory.FREQUENT, listOf("祈祷", "谢谢", "感谢", "pray", "thanks", "please")),
        EmojiEntry("💪", "muscle", EmojiCategory.FREQUENT, listOf("加油", "力量", "strong", "muscle", "flex")),
        EmojiEntry("🤝", "handshake", EmojiCategory.FREQUENT, listOf("握手", "合作", "handshake", "deal", "agree")),
        EmojiEntry("👋", "wave", EmojiCategory.FREQUENT, listOf("你好", "再见", "hi", "bye", "wave")),
        EmojiEntry("😱", "scream", EmojiCategory.FREQUENT, listOf("吓死", "惊恐", "scream", "shock", "horror")),
        EmojiEntry("🤷", "shrug", EmojiCategory.FREQUENT, listOf("摊手", "不知道", "shrug", "dunno", "whatever")),
        EmojiEntry("👏", "clap", EmojiCategory.FREQUENT, listOf("鼓掌", "棒", "clap", "applause", "bravo")),
        EmojiEntry("💕", "two_hearts", EmojiCategory.FREQUENT, listOf("双心", "喜欢", "love", "hearts", "affection")),
        EmojiEntry("🥳", "partying_face", EmojiCategory.FREQUENT, listOf("派对脸", "庆祝", "party", "celebrate", "birthday")),
        EmojiEntry("💖", "sparkling_heart", EmojiCategory.FREQUENT, listOf("闪亮心", "喜欢", "sparkling", "love", "heart")),
        EmojiEntry("🫠", "melting_face", EmojiCategory.FREQUENT, listOf("融化", "热化了", "melt", "hot")),
        EmojiEntry("🫡", "saluting_face", EmojiCategory.FREQUENT, listOf("敬礼", "respect", "salute")),
        EmojiEntry("😃", "smiley", EmojiCategory.EXPRESSIONS, listOf("开心", "大笑", "smile", "happy", "grin")),
        EmojiEntry("😄", "smile", EmojiCategory.EXPRESSIONS, listOf("开心", "笑脸", "smile", "happy")),
        EmojiEntry("😁", "grin", EmojiCategory.EXPRESSIONS, listOf("嘻嘻", "咧嘴笑", "grin", "beam")),
        EmojiEntry("😆", "laughing", EmojiCategory.EXPRESSIONS, listOf("哈哈", "大笑", "laugh", "haha")),
        EmojiEntry("😉", "wink", EmojiCategory.EXPRESSIONS, listOf("眨眼", "wink", "hint")),
        EmojiEntry("😋", "yum", EmojiCategory.EXPRESSIONS, listOf("好吃", "美味", "yummy", "tasty", "delicious")),
        EmojiEntry("😛", "stuck_out_tongue", EmojiCategory.EXPRESSIONS, listOf("吐舌", "调皮", "tongue", "playful")),
        EmojiEntry("😜", "stuck_out_tongue_winking_eye", EmojiCategory.EXPRESSIONS, listOf("调皮", "眨眼吐舌", "wink", "tongue", "silly")),
        EmojiEntry("😝", "stuck_out_tongue_closed_eyes", EmojiCategory.EXPRESSIONS, listOf("晕吐舌", "闭眼吐舌", "tongue", "dizzy")),
        EmojiEntry("🤗", "hugging_face", EmojiCategory.EXPRESSIONS, listOf("抱抱", "拥抱", "hug", "embrace")),
        EmojiEntry("🤩", "star_struck", EmojiCategory.EXPRESSIONS, listOf("好棒", "星星眼", "star", "excited", "amazing")),
        EmojiEntry("🤤", "drooling_face", EmojiCategory.EXPRESSIONS, listOf("流口水", "馋", "drool", "yummy")),
        EmojiEntry("🤑", "money_mouth_face", EmojiCategory.EXPRESSIONS, listOf("发财", "有钱", "money", "rich")),
        EmojiEntry("🤭", "hand_over_mouth", EmojiCategory.EXPRESSIONS, listOf("捂嘴笑", "偷笑", "捂脸", "oops", "giggle")),
        EmojiEntry("🤫", "shushing_face", EmojiCategory.EXPRESSIONS, listOf("嘘", "安静", "shush", "quiet", "silence")),
        EmojiEntry("🤥", "lying_face", EmojiCategory.EXPRESSIONS, listOf("说谎", "匹诺曹", "lie", "pinocchio")),
        EmojiEntry("😐", "neutral_face", EmojiCategory.EXPRESSIONS, listOf("无语", "面无表情", "neutral", "meh")),
        EmojiEntry("😑", "expressionless", EmojiCategory.EXPRESSIONS, listOf("无语", "无表情", "expressionless", "blank")),
        EmojiEntry("😶", "no_mouth", EmojiCategory.EXPRESSIONS, listOf("沉默", "没嘴", "silent", "mute")),
        EmojiEntry("😏", "smirk", EmojiCategory.EXPRESSIONS, listOf("坏笑", "得意", "smirk", "sneaky")),
        EmojiEntry("😒", "unamused", EmojiCategory.EXPRESSIONS, listOf("不高兴", "不满", "unamused", "bored")),
        EmojiEntry("🙄", "eye_roll", EmojiCategory.EXPRESSIONS, listOf("翻白眼", "无语", "roll", "whatever")),
        EmojiEntry("😬", "grimacing", EmojiCategory.EXPRESSIONS, listOf("尴尬", "龇牙", "grimace", "awkward")),
        EmojiEntry("😤", "triumph", EmojiCategory.EXPRESSIONS, listOf("哼", "气愤", "huff", "angry")),
        EmojiEntry("😠", "angry", EmojiCategory.EXPRESSIONS, listOf("生气", "愤怒", "angry", "mad")),
        EmojiEntry("😡", "rage", EmojiCategory.EXPRESSIONS, listOf("暴怒", "很生气", "rage", "furious")),
        EmojiEntry("😳", "flushed", EmojiCategory.EXPRESSIONS, listOf("脸红", "害羞", "flushed", "embarrassed")),
        EmojiEntry("🥵", "hot_face", EmojiCategory.EXPRESSIONS, listOf("热", "好热", "hot", "heat")),
        EmojiEntry("🥶", "cold_face", EmojiCategory.EXPRESSIONS, listOf("冷", "好冷", "cold", "freezing")),
        EmojiEntry("😨", "frightened", EmojiCategory.EXPRESSIONS, listOf("恐惧", "吓到", "frightened", "scared")),
        EmojiEntry("😰", "anxious", EmojiCategory.EXPRESSIONS, listOf("焦虑", "紧张", "anxious", "nervous")),
        EmojiEntry("😥", "disappointed_relieved", EmojiCategory.EXPRESSIONS, listOf("失落又安心", "phew", "relieved")),
        EmojiEntry("😢", "crying", EmojiCategory.EXPRESSIONS, listOf("哭", "伤心", "cry", "sad")),
        EmojiEntry("😞", "disappointed", EmojiCategory.EXPRESSIONS, listOf("失望", "失落", "disappointed", "sad")),
        EmojiEntry("😓", "downcast_sweat", EmojiCategory.EXPRESSIONS, listOf("冷汗", "汗", "sweat", "stress")),
        EmojiEntry("😩", "weary", EmojiCategory.EXPRESSIONS, listOf("累", "疲乏", "weary", "tired")),
        EmojiEntry("😫", "tired_face", EmojiCategory.EXPRESSIONS, listOf("好累", "疲惫", "tired", "exhausted")),
        EmojiEntry("🥱", "yawning_face", EmojiCategory.EXPRESSIONS, listOf("打哈欠", "困", "yawn", "sleepy")),
        EmojiEntry("🤯", "exploding_head", EmojiCategory.EXPRESSIONS, listOf("爆炸头", "震惊", "mind", "blown", "shocked")),
        EmojiEntry("🤪", "zany_face", EmojiCategory.EXPRESSIONS, listOf("疯癫", "搞怪", "crazy", "zany", "wild")),
        EmojiEntry("🤨", "raised_eyebrow", EmojiCategory.EXPRESSIONS, listOf("挑眉", "怀疑", "skeptical", "suspicious")),
        EmojiEntry("😇", "innocent", EmojiCategory.EXPRESSIONS, listOf("天使", "无辜", "innocent", "angel", "halo")),
        EmojiEntry("🥴", "woozy_face", EmojiCategory.EXPRESSIONS, listOf("晕", "迷糊", "woozy", "dizzy")),
        EmojiEntry("🤢", "nauseated_face", EmojiCategory.EXPRESSIONS, listOf("恶心", "想吐", "nauseated", "sick")),
        EmojiEntry("🤮", "vomiting_face", EmojiCategory.EXPRESSIONS, listOf("吐了", "呕", "vomit", "sick")),
        EmojiEntry("🤡", "clown_face", EmojiCategory.EXPRESSIONS, listOf("小丑", "搞笑", "clown", "funny")),
        EmojiEntry("💩", "poop", EmojiCategory.EXPRESSIONS, listOf("便便", "屎", "poop", "shit")),
        EmojiEntry("👻", "ghost", EmojiCategory.EXPRESSIONS, listOf("鬼", "幽灵", "ghost", "spooky")),
        EmojiEntry("💀", "skull", EmojiCategory.EXPRESSIONS, listOf("骷髅", "死", "skull", "dead")),
        EmojiEntry("👽", "alien", EmojiCategory.EXPRESSIONS, listOf("外星人", "ET", "alien", "UFO")),
        EmojiEntry("🤖", "robot", EmojiCategory.EXPRESSIONS, listOf("机器人", "robot", "machine")),
        EmojiEntry("😺", "smiley_cat", EmojiCategory.EXPRESSIONS, listOf("猫笑", "cat", "smile")),
        EmojiEntry("😸", "smile_cat", EmojiCategory.EXPRESSIONS, listOf("猫微笑", "cat", "grin")),
        EmojiEntry("😹", "joy_cat", EmojiCategory.EXPRESSIONS, listOf("猫笑哭", "cat", "laugh")),
        EmojiEntry("😻", "heart_eyes_cat", EmojiCategory.EXPRESSIONS, listOf("猫花痴", "cat", "love")),
        EmojiEntry("😼", "smirk_cat", EmojiCategory.EXPRESSIONS, listOf("猫坏笑", "cat", "smirk")),
        EmojiEntry("😽", "kissing_cat", EmojiCategory.EXPRESSIONS, listOf("猫亲亲", "cat", "kiss")),
        EmojiEntry("🙀", "scream_cat", EmojiCategory.EXPRESSIONS, listOf("猫惊恐", "cat", "scream")),
        EmojiEntry("😿", "crying_cat", EmojiCategory.EXPRESSIONS, listOf("猫哭", "cat", "cry")),
        EmojiEntry("😾", "pouting_cat", EmojiCategory.EXPRESSIONS, listOf("猫生气", "cat", "angry")),
        EmojiEntry("🙊", "see_no_evil", EmojiCategory.EXPRESSIONS, listOf("捂嘴", "不看", "monkey", "see", "no")),
        EmojiEntry("🙉", "hear_no_evil", EmojiCategory.EXPRESSIONS, listOf("捂耳", "不听", "monkey", "hear", "no")),
        EmojiEntry("🙈", "speak_no_evil", EmojiCategory.EXPRESSIONS, listOf("捂眼", "不说", "monkey", "speak", "no")),
        EmojiEntry("😘", "kissing_heart", EmojiCategory.EXPRESSIONS, listOf("飞吻", "亲亲", "kiss", "love")),
        EmojiEntry("😗", "kissing", EmojiCategory.EXPRESSIONS, listOf("亲", "kiss")),
        EmojiEntry("😙", "kissing_smiling_eyes", EmojiCategory.EXPRESSIONS, listOf("微笑亲", "kiss", "smile")),
        EmojiEntry("😚", "kissing_closed_eyes", EmojiCategory.EXPRESSIONS, listOf("闭眼亲", "kiss")),
        EmojiEntry("😌", "relieved", EmojiCategory.EXPRESSIONS, listOf("释然", "安心", "relieved", "peace")),
        EmojiEntry("🤓", "nerd_face", EmojiCategory.EXPRESSIONS, listOf("书呆子", "学霸", "nerd", "geek")),
        EmojiEntry("😈", "smiling_imp", EmojiCategory.EXPRESSIONS, listOf("小恶魔", "坏", "devil", "evil")),
        EmojiEntry("👿", "imp", EmojiCategory.EXPRESSIONS, listOf("恶魔", "生气恶魔", "devil", "angry")),
        EmojiEntry("👹", "ogre", EmojiCategory.EXPRESSIONS, listOf("鬼", "妖怪", "ogre", "monster")),
        EmojiEntry("👺", "goblin", EmojiCategory.EXPRESSIONS, listOf("天狗", "妖怪", "goblin", "mask")),
        EmojiEntry("😴", "sleeping", EmojiCategory.EXPRESSIONS, listOf("睡觉", "困", "sleep", "zzz")),
        EmojiEntry("🫥", "dotted_line_face", EmojiCategory.EXPRESSIONS, listOf("消失", "隐身", "invisible", "disappear")),
        EmojiEntry("😱", "fearful", EmojiCategory.EXPRESSIONS, listOf("害怕", "惊恐", "fear", "scared")),
        EmojiEntry("😷", "mask", EmojiCategory.EXPRESSIONS, listOf("口罩", "生病", "mask", "sick")),
        EmojiEntry("🤒", "face_with_thermometer", EmojiCategory.EXPRESSIONS, listOf("发烧", "体温计", "fever", "sick")),
        EmojiEntry("🤕", "face_with_head_bandage", EmojiCategory.EXPRESSIONS, listOf("受伤", "绷带", "hurt", "bandage")),
        EmojiEntry("🤧", "sneezing_face", EmojiCategory.EXPRESSIONS, listOf("打喷嚏", "sneeze", "cold")),
        EmojiEntry("👋", "wave_gesture", EmojiCategory.GESTURES, listOf("挥手", "你好", "bye", "hi", "wave")),
        EmojiEntry("🤚", "raised_back_of_hand", EmojiCategory.GESTURES, listOf("手背", "停", "stop", "hand")),
        EmojiEntry("🖐️", "raised_hand_with_fingers_splayed", EmojiCategory.GESTURES, listOf("五指张开", "spread", "hand", "five")),
        EmojiEntry("✋", "raised_hand", EmojiCategory.GESTURES, listOf("举手", "停", "hand", "stop", "high_five")),
        EmojiEntry("🖖", "vulcan_salute", EmojiCategory.GESTURES, listOf("瓦肯礼", "星际迷航", "vulcan", "spock", "live long")),
        EmojiEntry("👌", "ok_hand", EmojiCategory.GESTURES, listOf("OK", "好", "ok", "perfect")),
        EmojiEntry("🤌", "pinched_fingers", EmojiCategory.GESTURES, listOf("捏手指", "意大利手势", "pinch", "italian")),
        EmojiEntry("🤏", "pinching_hand", EmojiCategory.GESTURES, listOf("一点点", "微小", "tiny", "small", "pinch")),
        EmojiEntry("✌️", "victory_hand", EmojiCategory.GESTURES, listOf("胜利", "耶", "peace", "victory", "two")),
        EmojiEntry("🤞", "crossed_fingers", EmojiCategory.GESTURES, listOf("好运", "交叉手指", "luck", "hope", "cross")),
        EmojiEntry("🤟", "love_you_gesture", EmojiCategory.GESTURES, listOf("爱你", "rock", "love", "ILY")),
        EmojiEntry("🤘", "sign_of_the_horns", EmojiCategory.GESTURES, listOf("摇滚", "rock", "horns", "metal")),
        EmojiEntry("🤙", "call_me_hand", EmojiCategory.GESTURES, listOf("打电话", "call", "shaka", "hang loose")),
        EmojiEntry("👈", "point_left", EmojiCategory.GESTURES, listOf("左", "那边", "left", "point")),
        EmojiEntry("👉", "point_right", EmojiCategory.GESTURES, listOf("右", "这边", "right", "point")),
        EmojiEntry("👆", "point_up_2", EmojiCategory.GESTURES, listOf("上面", "up", "point")),
        EmojiEntry("👇", "point_down", EmojiCategory.GESTURES, listOf("下面", "down", "point")),
        EmojiEntry("☝️", "index_finger_up", EmojiCategory.GESTURES, listOf("一", "等等", "one", "wait")),
        EmojiEntry("🫵", "pointing_at_viewer", EmojiCategory.GESTURES, listOf("指你", "就是你", "point", "you")),
        EmojiEntry("✊", "fist", EmojiCategory.GESTURES, listOf("拳头", "加油", "fist", "fight")),
        EmojiEntry("👊", "punch", EmojiCategory.GESTURES, listOf("出拳", "打", "punch", "fist", "bump")),
        EmojiEntry("🤛", "left_fist", EmojiCategory.GESTURES, listOf("左拳", "left", "fist", "bump")),
        EmojiEntry("🤜", "right_fist", EmojiCategory.GESTURES, listOf("右拳", "right", "fist", "bump")),
        EmojiEntry("👏", "clap_gesture", EmojiCategory.GESTURES, listOf("鼓掌", "棒", "clap", "applause")),
        EmojiEntry("🙌", "raised_hands", EmojiCategory.GESTURES, listOf("举手庆祝", "太棒了", "celebration", "hooray")),
        EmojiEntry("🫶", "heart_hands", EmojiCategory.GESTURES, listOf("比心", "爱心手", "heart", "love", "hands")),
        EmojiEntry("👐", "open_hands", EmojiCategory.GESTURES, listOf("张开手", "拥抱", "open", "hug")),
        EmojiEntry("🤲", "palms_up", EmojiCategory.GESTURES, listOf("捧手", "prayer", "palms", "up")),
        EmojiEntry("🤝", "handshake_gesture", EmojiCategory.GESTURES, listOf("握手", "合作", "handshake", "deal")),
        EmojiEntry("🙏", "pray_gesture", EmojiCategory.GESTURES, listOf("祈祷", "谢谢", "pray", "thanks")),
        EmojiEntry("✍️", "writing_hand", EmojiCategory.GESTURES, listOf("写字", "write", "pen")),
        EmojiEntry("💅", "nail_care", EmojiCategory.GESTURES, listOf("美甲", "漂亮", "nail", "polish", "fab")),
        EmojiEntry("🦶", "foot", EmojiCategory.GESTURES, listOf("脚", "foot", "kick")),
        EmojiEntry("🦵", "leg_gesture", EmojiCategory.GESTURES, listOf("腿", "leg", "kick")),
        EmojiEntry("🦿", "mechanical_leg", EmojiCategory.GESTURES, listOf("机械腿", "robot", "leg")),
        EmojiEntry("🦾", "mechanical_arm", EmojiCategory.GESTURES, listOf("机械臂", "robot", "arm")),
        EmojiEntry("💪", "muscle_gesture", EmojiCategory.GESTURES, listOf("加油", "肌肉", "strong", "muscle", "arm")),
        EmojiEntry("🫰", "hand_with_index_and_thumb_crossed", EmojiCategory.GESTURES, listOf("比心手", "小爱心", "heart", "love", "snap")),
        EmojiEntry("🤳", "selfie", EmojiCategory.GESTURES, listOf("自拍", "selfie", "phone")),
        EmojiEntry("🙅", "no_good", EmojiCategory.GESTURES, listOf("不行", "拒绝", "no", "refuse")),
        EmojiEntry("🐶", "dog", EmojiCategory.ANIMALS, listOf("狗", "狗狗", "dog", "puppy")),
        EmojiEntry("🐱", "cat_animal", EmojiCategory.ANIMALS, listOf("猫", "猫咪", "cat", "kitty")),
        EmojiEntry("🐭", "mouse", EmojiCategory.ANIMALS, listOf("老鼠", "鼠", "mouse")),
        EmojiEntry("🐹", "hamster", EmojiCategory.ANIMALS, listOf("仓鼠", "hamster")),
        EmojiEntry("🐰", "rabbit", EmojiCategory.ANIMALS, listOf("兔子", "兔兔", "rabbit", "bunny")),
        EmojiEntry("🦊", "fox", EmojiCategory.ANIMALS, listOf("狐狸", "fox")),
        EmojiEntry("🐻", "bear", EmojiCategory.ANIMALS, listOf("熊", "bear")),
        EmojiEntry("🐼", "panda", EmojiCategory.ANIMALS, listOf("熊猫", "国宝", "panda")),
        EmojiEntry("🐨", "koala", EmojiCategory.ANIMALS, listOf("考拉", "树袋熊", "koala")),
        EmojiEntry("🐯", "tiger", EmojiCategory.ANIMALS, listOf("老虎", "虎", "tiger")),
        EmojiEntry("🦁", "lion", EmojiCategory.ANIMALS, listOf("狮子", "lion")),
        EmojiEntry("🐮", "cow", EmojiCategory.ANIMALS, listOf("牛", "奶牛", "cow")),
        EmojiEntry("🐷", "pig", EmojiCategory.ANIMALS, listOf("猪", "猪猪", "pig")),
        EmojiEntry("🐸", "frog", EmojiCategory.ANIMALS, listOf("青蛙", "蛙", "frog")),
        EmojiEntry("🐵", "monkey", EmojiCategory.ANIMALS, listOf("猴子", "monkey")),
        EmojiEntry("🐔", "chicken", EmojiCategory.ANIMALS, listOf("鸡", "小鸡", "chicken")),
        EmojiEntry("🐧", "penguin", EmojiCategory.ANIMALS, listOf("企鹅", "penguin")),
        EmojiEntry("🐦", "bird", EmojiCategory.ANIMALS, listOf("鸟", "bird")),
        EmojiEntry("🐤", "baby_chick", EmojiCategory.ANIMALS, listOf("小鸡", "雏鸡", "chick")),
        EmojiEntry("🦆", "duck", EmojiCategory.ANIMALS, listOf("鸭子", "duck")),
        EmojiEntry("🦅", "eagle", EmojiCategory.ANIMALS, listOf("鹰", "老鹰", "eagle")),
        EmojiEntry("🦉", "owl", EmojiCategory.ANIMALS, listOf("猫头鹰", "owl")),
        EmojiEntry("🦇", "bat", EmojiCategory.ANIMALS, listOf("蝙蝠", "bat")),
        EmojiEntry("🐺", "wolf", EmojiCategory.ANIMALS, listOf("狼", "wolf")),
        EmojiEntry("🐗", "boar", EmojiCategory.ANIMALS, listOf("野猪", "boar")),
        EmojiEntry("🐴", "horse", EmojiCategory.ANIMALS, listOf("马", "horse")),
        EmojiEntry("🦄", "unicorn", EmojiCategory.ANIMALS, listOf("独角兽", "unicorn")),
        EmojiEntry("🐝", "bee", EmojiCategory.ANIMALS, listOf("蜜蜂", "bee", "honey")),
        EmojiEntry("🪱", "worm", EmojiCategory.ANIMALS, listOf("虫子", "蠕虫", "worm")),
        EmojiEntry("🐛", "bug", EmojiCategory.ANIMALS, listOf("虫", "bug")),
        EmojiEntry("🦋", "butterfly", EmojiCategory.ANIMALS, listOf("蝴蝶", "butterfly")),
        EmojiEntry("🐌", "snail", EmojiCategory.ANIMALS, listOf("蜗牛", "snail")),
        EmojiEntry("🐞", "ladybug", EmojiCategory.ANIMALS, listOf("瓢虫", "ladybug")),
        EmojiEntry("🐜", "ant", EmojiCategory.ANIMALS, listOf("蚂蚁", "ant")),
        EmojiEntry("🪰", "fly_insect", EmojiCategory.ANIMALS, listOf("苍蝇", "fly")),
        EmojiEntry("🪲", "beetle", EmojiCategory.ANIMALS, listOf("甲虫", "beetle")),
        EmojiEntry("🦫", "beaver", EmojiCategory.ANIMALS, listOf("海狸", "beaver")),
        EmojiEntry("🦭", "otter", EmojiCategory.ANIMALS, listOf("水獭", "otter")),
        EmojiEntry("🦬", "hippo", EmojiCategory.ANIMALS, listOf("河马", "hippo")),
        EmojiEntry("🦔", "hedgehog", EmojiCategory.ANIMALS, listOf("刺猬", "hedgehog")),
        EmojiEntry("🦃", "turkey", EmojiCategory.ANIMALS, listOf("火鸡", "turkey")),
        EmojiEntry("🦩", "sloth", EmojiCategory.ANIMALS, listOf("树懒", "sloth")),
        EmojiEntry("🦚", "peacock", EmojiCategory.ANIMALS, listOf("孔雀", "peacock")),
        EmojiEntry("🦜", "parrot", EmojiCategory.ANIMALS, listOf("鹦鹉", "parrot")),
        EmojiEntry("🦛", "kangaroo", EmojiCategory.ANIMALS, listOf("袋鼠", "kangaroo")),
        EmojiEntry("🦥", "llama", EmojiCategory.ANIMALS, listOf("羊驼", "草泥马", "llama")),
        EmojiEntry("🦢", "swan", EmojiCategory.ANIMALS, listOf("天鹅", "swan")),
        EmojiEntry("🦓", "zebra", EmojiCategory.ANIMALS, listOf("斑马", "zebra")),
        EmojiEntry("🐙", "octopus", EmojiCategory.ANIMALS, listOf("章鱼", "octopus")),
        EmojiEntry("🦑", "squid", EmojiCategory.ANIMALS, listOf("鱿鱼", "squid")),
        EmojiEntry("🦐", "shrimp", EmojiCategory.ANIMALS, listOf("虾", "shrimp")),
        EmojiEntry("🦞", "lobster", EmojiCategory.ANIMALS, listOf("龙虾", "lobster")),
        EmojiEntry("🦀", "crab", EmojiCategory.ANIMALS, listOf("螃蟹", "crab")),
        EmojiEntry("🐡", "blowfish", EmojiCategory.ANIMALS, listOf("河豚", "blowfish")),
        EmojiEntry("🐠", "tropical_fish", EmojiCategory.ANIMALS, listOf("热带鱼", "fish")),
        EmojiEntry("🐟", "fish", EmojiCategory.ANIMALS, listOf("鱼", "fish")),
        EmojiEntry("🐬", "dolphin", EmojiCategory.ANIMALS, listOf("海豚", "dolphin")),
        EmojiEntry("🐋", "whale", EmojiCategory.ANIMALS, listOf("鲸鱼", "whale")),
        EmojiEntry("🦈", "shark", EmojiCategory.ANIMALS, listOf("鲨鱼", "shark")),
        EmojiEntry("🐊", "crocodile", EmojiCategory.ANIMALS, listOf("鳄鱼", "crocodile")),
        EmojiEntry("🍎", "apple", EmojiCategory.FOOD, listOf("苹果", "apple")),
        EmojiEntry("🍐", "pear", EmojiCategory.FOOD, listOf("梨", "pear")),
        EmojiEntry("🍊", "orange", EmojiCategory.FOOD, listOf("橙子", "橘子", "orange")),
        EmojiEntry("🍋", "lemon", EmojiCategory.FOOD, listOf("柠檬", "lemon")),
        EmojiEntry("🍌", "banana", EmojiCategory.FOOD, listOf("香蕉", "banana")),
        EmojiEntry("🍉", "watermelon", EmojiCategory.FOOD, listOf("西瓜", "watermelon")),
        EmojiEntry("🍇", "grapes", EmojiCategory.FOOD, listOf("葡萄", "grapes")),
        EmojiEntry("🍓", "strawberry", EmojiCategory.FOOD, listOf("草莓", "strawberry")),
        EmojiEntry("🫐", "blueberries", EmojiCategory.FOOD, listOf("蓝莓", "blueberry")),
        EmojiEntry("🍈", "melon", EmojiCategory.FOOD, listOf("哈密瓜", "melon")),
        EmojiEntry("🍒", "cherries", EmojiCategory.FOOD, listOf("樱桃", "cherries")),
        EmojiEntry("🍑", "peach_food", EmojiCategory.FOOD, listOf("桃子", "peach")),
        EmojiEntry("🥭", "mango", EmojiCategory.FOOD, listOf("芒果", "mango")),
        EmojiEntry("🍍", "pineapple", EmojiCategory.FOOD, listOf("菠萝", "pineapple")),
        EmojiEntry("🥥", "coconut", EmojiCategory.FOOD, listOf("椰子", "coconut")),
        EmojiEntry("🥝", "kiwi", EmojiCategory.FOOD, listOf("猕猴桃", "奇异果", "kiwi")),
        EmojiEntry("🍅", "tomato", EmojiCategory.FOOD, listOf("番茄", "西红柿", "tomato")),
        EmojiEntry("🍆", "eggplant", EmojiCategory.FOOD, listOf("茄子", "eggplant")),
        EmojiEntry("🥑", "avocado", EmojiCategory.FOOD, listOf("牛油果", "鳄梨", "avocado")),
        EmojiEntry("🥦", "broccoli", EmojiCategory.FOOD, listOf("西兰花", "broccoli")),
        EmojiEntry("🥬", "leafy_green", EmojiCategory.FOOD, listOf("青菜", "白菜", "green", "vegetable")),
        EmojiEntry("🥒", "cucumber", EmojiCategory.FOOD, listOf("黄瓜", "cucumber")),
        EmojiEntry("🌶️", "hot_pepper", EmojiCategory.FOOD, listOf("辣椒", "辣", "pepper", "spicy")),
        EmojiEntry("🫑", "bell_pepper", EmojiCategory.FOOD, listOf("甜椒", "灯笼椒", "pepper")),
        EmojiEntry("🌽", "corn", EmojiCategory.FOOD, listOf("玉米", "corn")),
        EmojiEntry("🥕", "carrot", EmojiCategory.FOOD, listOf("胡萝卜", "carrot")),
        EmojiEntry("🧄", "garlic", EmojiCategory.FOOD, listOf("大蒜", "蒜", "garlic")),
        EmojiEntry("🧅", "onion", EmojiCategory.FOOD, listOf("洋葱", "onion")),
        EmojiEntry("🥔", "potato", EmojiCategory.FOOD, listOf("土豆", "potato")),
        EmojiEntry("🍠", "sweet_potato", EmojiCategory.FOOD, listOf("红薯", "地瓜", "sweet", "potato")),
        EmojiEntry("🍞", "bread", EmojiCategory.FOOD, listOf("面包", "bread")),
        EmojiEntry("🥐", "croissant", EmojiCategory.FOOD, listOf("牛角包", "croissant")),
        EmojiEntry("🥖", "baguette_bread", EmojiCategory.FOOD, listOf("法棍", "baguette")),
        EmojiEntry("🫓", "flatbread", EmojiCategory.FOOD, listOf("烤饼", "馕", "flatbread", "naan")),
        EmojiEntry("🥨", "pretzel", EmojiCategory.FOOD, listOf("椒盐卷饼", "pretzel")),
        EmojiEntry("🧀", "cheese", EmojiCategory.FOOD, listOf("奶酪", "芝士", "cheese")),
        EmojiEntry("🥚", "egg", EmojiCategory.FOOD, listOf("蛋", "鸡蛋", "egg")),
        EmojiEntry("🍳", "fried_egg", EmojiCategory.FOOD, listOf("煎蛋", "荷包蛋", "fried", "egg")),
        EmojiEntry("🧈", "butter", EmojiCategory.FOOD, listOf("黄油", "奶油", "butter")),
        EmojiEntry("🥞", "pancakes", EmojiCategory.FOOD, listOf("煎饼", "松饼", "pancake")),
        EmojiEntry("🧇", "waffle", EmojiCategory.FOOD, listOf("华夫饼", "waffle")),
        EmojiEntry("🥓", "bacon", EmojiCategory.FOOD, listOf("培根", "bacon")),
        EmojiEntry("🥩", "steak", EmojiCategory.FOOD, listOf("牛排", "肉", "steak", "meat")),
        EmojiEntry("🍗", "poultry_leg", EmojiCategory.FOOD, listOf("鸡腿", "poultry", "leg")),
        EmojiEntry("🍖", "meat_on_bone", EmojiCategory.FOOD, listOf("排骨", "meat", "bone")),
        EmojiEntry("🌭", "hotdog", EmojiCategory.FOOD, listOf("热狗", "hotdog")),
        EmojiEntry("🍔", "hamburger", EmojiCategory.FOOD, listOf("汉堡", "hamburger", "burger")),
        EmojiEntry("🍟", "fries", EmojiCategory.FOOD, listOf("薯条", "fries", "chips")),
        EmojiEntry("🍕", "pizza", EmojiCategory.FOOD, listOf("披萨", "比萨", "pizza")),
        EmojiEntry("🫔", "fondue", EmojiCategory.FOOD, listOf("火锅", "芝士锅", "fondue", "hotpot")),
        EmojiEntry("🥪", "sandwich", EmojiCategory.FOOD, listOf("三明治", "sandwich")),
        EmojiEntry("🌮", "taco", EmojiCategory.FOOD, listOf("塔可", "taco")),
        EmojiEntry("🌯", "burrito", EmojiCategory.FOOD, listOf("卷饼", "burrito")),
        EmojiEntry("🥙", "stuffed_flatbread", EmojiCategory.FOOD, listOf("口袋饼", "肉夹馍", "pita")),
        EmojiEntry("🧆", "falafel", EmojiCategory.FOOD, listOf("法拉费", "炸丸子", "falafel")),
        EmojiEntry("🥗", "salad", EmojiCategory.FOOD, listOf("沙拉", "salad")),
        EmojiEntry("🥘", "shallow_pan_of_food", EmojiCategory.FOOD, listOf("炖菜", "stew", "pan")),
        EmojiEntry("🍝", "spaghetti", EmojiCategory.FOOD, listOf("意面", "意大利面", "spaghetti", "pasta")),
        EmojiEntry("🍜", "ramen", EmojiCategory.FOOD, listOf("拉面", "面条", "ramen", "noodle")),
        EmojiEntry("🍲", "stew_food", EmojiCategory.FOOD, listOf("汤", "炖汤", "stew", "soup")),
        EmojiEntry("🍛", "curry", EmojiCategory.FOOD, listOf("咖喱", "curry")),
        EmojiEntry("🍣", "sushi", EmojiCategory.FOOD, listOf("寿司", "sushi")),
        EmojiEntry("🍱", "bento", EmojiCategory.FOOD, listOf("便当", "盒饭", "bento")),
        EmojiEntry("🥟", "dumpling", EmojiCategory.FOOD, listOf("饺子", "dumpling")),
        EmojiEntry("🦪", "oyster", EmojiCategory.FOOD, listOf("生蚝", "牡蛎", "oyster")),
        EmojiEntry("🍤", "fried_shrimp", EmojiCategory.FOOD, listOf("炸虾", "天妇罗", "shrimp", "tempura")),
        EmojiEntry("🍙", "rice_ball", EmojiCategory.FOOD, listOf("饭团", "rice", "ball")),
        EmojiEntry("🍚", "rice", EmojiCategory.FOOD, listOf("米饭", "rice")),
        EmojiEntry("🍘", "rice_cracker", EmojiCategory.FOOD, listOf("仙贝", "米饼", "cracker")),
        EmojiEntry("🍥", "fish_cake", EmojiCategory.FOOD, listOf("鱼板", "鱼饼", "fish", "cake")),
        EmojiEntry("🥠", "fortune_cookie", EmojiCategory.FOOD, listOf("签语饼", "幸运饼", "fortune")),
        EmojiEntry("🥮", "moon_cake", EmojiCategory.FOOD, listOf("月饼", "moon", "cake")),
        EmojiEntry("🍢", "oden", EmojiCategory.FOOD, listOf("关东煮", "oden")),
        EmojiEntry("🍡", "dango", EmojiCategory.FOOD, listOf("团子", "dango")),
        EmojiEntry("🍧", "shaved_ice", EmojiCategory.FOOD, listOf("刨冰", "shaved", "ice")),
        EmojiEntry("🍨", "ice_cream", EmojiCategory.FOOD, listOf("冰淇淋", "ice", "cream")),
        EmojiEntry("🍦", "soft_ice_cream", EmojiCategory.FOOD, listOf("甜筒", "冰淇淋", "ice", "cream")),
        EmojiEntry("🍿", "popcorn", EmojiCategory.FOOD, listOf("爆米花", "popcorn")),
        EmojiEntry("🧃", "beverage_box", EmojiCategory.FOOD, listOf("饮料盒", "juice", "beverage"))
    )

    val emojis: List<EmojiEntry> get() = _emojis

    fun findByCategory(category: EmojiCategory): List<EmojiEntry> =
        _emojis.filter { it.category == category }

    fun searchEmoji(query: String): List<EmojiEntry> {
        val lowerQuery = query.lowercase()
        return _emojis.filter { entry ->
            entry.name.contains(lowerQuery, ignoreCase = true) ||
                entry.keywords.any { it.contains(lowerQuery, ignoreCase = true) }
        }
    }
}
